eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id : retail-customer-route
          uri: lb://retail-customer-service
          predicates:
            - Path=/retailCustomer/*
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: retailBankCircuitBreaker
                fallbackUri: forward:/fallback/retailBankFallback
