server:
  port: 8761

spring:
  application:
    name: retail-customer-service-registry
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  server:
    wait-time-in-ms-when-sync-empty: 0
